name: e_florista_bot
description: A flower delivery Telegram bot using teledart
environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  teledart: ^0.6.1
  dotenv: ^4.0.1


dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
